/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ItineraryRouteImport } from './routes/itinerary'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrintTripIdRouteImport } from './routes/print.$tripId'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryRoute = ItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintTripIdRoute = PrintTripIdRouteImport.update({
  id: '/print/$tripId',
  path: '/print/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/flights': typeof FlightsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hotels': typeof HotelsRoute
  '/itinerary': typeof ItineraryRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/register': typeof RegisterRoute
  '/trips': typeof TripsRoute
  '/api/chat': typeof ApiChatRoute
  '/print/$tripId': typeof PrintTripIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/flights': typeof FlightsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hotels': typeof HotelsRoute
  '/itinerary': typeof ItineraryRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/register': typeof RegisterRoute
  '/trips': typeof TripsRoute
  '/api/chat': typeof ApiChatRoute
  '/print/$tripId': typeof PrintTripIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/flights': typeof FlightsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hotels': typeof HotelsRoute
  '/itinerary': typeof ItineraryRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/register': typeof RegisterRoute
  '/trips': typeof TripsRoute
  '/api/chat': typeof ApiChatRoute
  '/print/$tripId': typeof PrintTripIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/flights'
    | '/forgot-password'
    | '/hotels'
    | '/itinerary'
    | '/login'
    | '/payment'
    | '/payment-success'
    | '/register'
    | '/trips'
    | '/api/chat'
    | '/print/$tripId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/flights'
    | '/forgot-password'
    | '/hotels'
    | '/itinerary'
    | '/login'
    | '/payment'
    | '/payment-success'
    | '/register'
    | '/trips'
    | '/api/chat'
    | '/print/$tripId'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/flights'
    | '/forgot-password'
    | '/hotels'
    | '/itinerary'
    | '/login'
    | '/payment'
    | '/payment-success'
    | '/register'
    | '/trips'
    | '/api/chat'
    | '/print/$tripId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  FlightsRoute: typeof FlightsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HotelsRoute: typeof HotelsRoute
  ItineraryRoute: typeof ItineraryRoute
  LoginRoute: typeof LoginRoute
  PaymentRoute: typeof PaymentRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  RegisterRoute: typeof RegisterRoute
  TripsRoute: typeof TripsRoute
  ApiChatRoute: typeof ApiChatRoute
  PrintTripIdRoute: typeof PrintTripIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary': {
      id: '/itinerary'
      path: '/itinerary'
      fullPath: '/itinerary'
      preLoaderRoute: typeof ItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/$tripId': {
      id: '/print/$tripId'
      path: '/print/$tripId'
      fullPath: '/print/$tripId'
      preLoaderRoute: typeof PrintTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  FlightsRoute: FlightsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HotelsRoute: HotelsRoute,
  ItineraryRoute: ItineraryRoute,
  LoginRoute: LoginRoute,
  PaymentRoute: PaymentRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  RegisterRoute: RegisterRoute,
  TripsRoute: TripsRoute,
  ApiChatRoute: ApiChatRoute,
  PrintTripIdRoute: PrintTripIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
